version: '3'
services:
  backend:
    container_name: jdk
    build:
      context: ../.
      dockerfile: Docker/jdk/Dockerfile
    ports:
      - "8000:8080"
    # command: mvn spring-boot:run -f backend
    volumes:
      - ../settings/maven-repo:/root/.m2
      - "../app:/usr/src/app/"
    tty: true
  db:
    container_name: mongod
    build:
      context: ../.
      dockerfile: Docker/mongo/Dockerfile
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
    tty: true
  server:
    container_name: serve
    build:
      context: ../.
      dockerfile: Docker/node/Dockerfile
    ports:
      - "8888:8888"
      - "8001:8000"
    volumes:
      - "../app:/usr/src/app/"
      - "/usr/src/app/middle-serve/node_modules/"
      - "/usr/src/app/client/node_modules/"
    tty: true