version: '3'
services:
  backend:
    container_name: jdk
    build:
      context: ../.
      dockerfile: Docker/jdk/Dockerfile
    # command: catalina.sh run
    ports:
      - "8000:8080"
    volumes:
      - ../maven-repo:/root/.m2
      - "../backend:/usr/src/backend"
    #   - ../m2-repo:/usr/share/maven/ref/.m2/repository
    tty: true
  db:
    container_name: mongod
    build:
      context: ../.
      dockerfile: Docker/mongo/Dockerfile
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    tty: true
  server:
    container_name: serve
    build:
      context: ../.
      dockerfile: Docker/node/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "../frontend:/usr/src/frontend/"
      - "/usr/src/backend/node_modules/"
    tty: true