version: '3'
services:
  backend:
    container_name: jdk
    build:
      context: ../.
      dockerfile: Docker/jdk/Dockerfile
    ports:
      - "8080:8080"
      - "35729:35729"
    command: gradle bootRun
    volumes:
      - ../settings/gradle:/home/gradle/.gradle
      - "../app/backend:/usr/src/app/backend"
    depends_on: 
      - db
    tty: true
  db:
    container_name: mongod
    build:
      context: ../.
      dockerfile: Docker/mongo/Dockerfile
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bdd
    tty: true
  server:
    container_name: serve
    build:
      context: ../.
      dockerfile: Docker/node/Dockerfile
    ports:
      - "8888:8888"
      - "8001:8000"
    volumes:
      - "../app:/usr/src/app/"
      - "/usr/src/app/middle-serve/node_modules/"
      - "/usr/src/app/client/node_modules/"
    tty: true