server:
    address: 0.0.0.0
    port: 8080
spring:
    devtools:
        restart:
            enabled: true
            additional-paths: .
    freemarker:
        cache: false
    thymeleaf:
        cache: false