server:
    address: 0.0.0.0
    port: 8080
spring:
    devtools:
        restart:
            enabled: true
            additional-paths: build/libs
        remote:
            proxy: 
                host: 0.0.0.0
                port: 35729
            secret: pwd
    thymeleaf:
        cache: false
    data:
        mongodb:
            uri: mongodb://db/bdd